from enum import EnumDict


class GreekLetters(EnumDict):
    # Lowercase Greek letters
    alpha   = "α"
    beta    = "β"
    gamma   = "γ"
    delta   = "δ"
    epsilon = "ε"
    zeta    = "ζ"
    eta     = "η"
    theta   = "θ"
    iota    = "ι"
    kappa   = "κ"
    lambda_ = "λ"   # lambda is a keyword in Python
    mu      = "μ"
    nu      = "ν"
    xi      = "ξ"
    omicron = "ο"
    pi      = "π"
    rho     = "ρ"
    sigma   = "σ"
    tau     = "τ"
    upsilon = "υ"
    phi     = "φ"
    chi     = "χ"
    psi     = "ψ"
    omega   = "ω"

    # Uppercase Greek letters
    Alpha   = "Α"
    Beta    = "Β"
    Gamma   = "Γ"
    Delta   = "Δ"
    Epsilon = "Ε"
    Zeta    = "Ζ"
    Eta     = "Η"
    Theta   = "Θ"
    Iota    = "Ι"
    Kappa   = "Κ"
    Lambda_ = "Λ"
    Mu      = "Μ"
    Nu      = "Ν"
    Xi      = "Ξ"
    Omicron = "Ο"
    Pi      = "Π"
    Rho     = "Ρ"
    Sigma   = "Σ"
    Tau     = "Τ"
    Upsilon = "Υ"
    Phi     = "Φ"
    Chi     = "Χ"
    Psi     = "Ψ"
    Omega   = "Ω"